apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: api-service
  app.kubernetes.io/name: api-service
kind: Kustomization
namespace: kubeflow
resources:
- overlays/application/application.yaml
