apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: katib
  app.kubernetes.io/name: katib-controller
configurations:
- overlays/istio/params.yaml
kind: Kustomization
namespace: kubeflow
resources:
- overlays/application/application.yaml
- overlays/istio/katib-ui-virtual-service.yaml
