apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: profiles
  app.kubernetes.io/name: profiles
configurations:
- overlays/istio/params.yaml
kind: Kustomization
namespace: kubeflow
resources:
- overlays/application/application.yaml
- overlays/istio/virtual-service.yaml
