apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: ml-pipeline-visualizationserver
resources:
- deployment.yaml
- service.yaml
images:
- name: gcr.io/ml-pipeline/visualization-server
  newTag: gcr.io-ml-pipeline-visualization-server-0.2.5
  newName: registry.cn-shanghai.aliyuncs.com/pai_product/k8s
