apiVersion: v1
data:
  credentials: |-
    {
       "gcs": {
           "gcsCredentialFileName": "gcloud-application-credentials.json"
       },
       "s3": {
           "s3AccessKeyIDName": "awsAccessKeyID",
           "s3SecretAccessKeyName": "awsSecretAccessKey"
       }
    }
  explainers: |-
    {
        "alibi": {
            "image" : "docker.io/seldonio/kfserving-alibiexplainer",
            "defaultImageVersion": "v0.3.0",
            "allowedImageVersions": [
               "v0.3.0"
            ]
        }
    }
  ingress: |-
    {
        "ingressGateway" : "kubeflow-gateway.kubeflow",
        "ingressService" : "istio-ingressgateway.istio-system.svc.cluster.local"
    }
  logger: |-
    {
        "image" : "registry.cn-shanghai.aliyuncs.com/pai_product/k8s:gcr.io-kfserving-logger-v0.3.0",
        "memoryRequest": "100Mi",
        "memoryLimit": "1Gi",
        "cpuRequest": "100m",
        "cpuLimit": "1"
    }
  predictors: |-
    {
        "tensorflow": {
            "image": "registry.cn-shanghai.aliyuncs.com/pai_product/k8s",
            "defaultImageVersion": "tensorflow-serving-1.14.0",
            "defaultGpuImageVersion": "tensorflow-serving-1.14.0-gpu",
            "allowedImageVersions": [
               "tensorflow-serving-1.11.0",
               "tensorflow-serving-1.11.0-gpu",
               "tensorflow-serving-1.12.0",
               "tensorflow-serving-1.12.0-gpu",
               "tensorflow-serving-1.13.0",
               "tensorflow-serving-1.13.0-gpu",
               "tensorflow-serving-1.14.0",
               "tensorflow-serving-1.14.0-gpu"
            ]
        },
        "onnx": {
            "image": "mcr.microsoft.com/onnxruntime/server",
            "defaultImageVersion": "v0.5.1",
            "allowedImageVersions": [
               "v0.5.1"
            ]
        },
        "sklearn": {
            "image": "registry.cn-shanghai.aliyuncs.com/pai_product/k8s",
            "defaultImageVersion": "gcr.io-kfserving-sklearnserver-v0.3.0",
            "allowedImageVersions": [
               "gcr.io-kfserving-sklearnserver-v0.3.0"
            ]
        },
        "xgboost": {
            "image": "registry.cn-shanghai.aliyuncs.com/pai_product/k8s",
            "defaultImageVersion": "gcr.io-kfserving-xgbserver-v0.3.0",
            "allowedImageVersions": [
               "gcr.io-kfserving-xgbserver-v0.3.0"
            ]
        },
        "pytorch": {
            "image": "registry.cn-shanghai.aliyuncs.com/pai_product/k8s",
            "defaultImageVersion": "gcr.io-kfserving-pytorchserver-v0.3.0",
            "defaultGpuImageVersion": "gcr.io-kfserving-pytorchserver-v0.3.0-gpu",
            "allowedImageVersions": [
               "gcr.io-kfserving-pytorchserver-v0.3.0",
               "gcr.io-kfserving-pytorchserver-v0.3.0-gpu"
            ]
        },
        "tensorrt": {
            "image": "registry.cn-shanghai.aliyuncs.com/pai_product/k8s",
            "defaultImageVersion": "1nvcr.io-nvidia-tensorrtserver-9.05-py3",
            "allowedImageVersions": [
               "nvcr.io-nvidia-tensorrtserver-19.05-py3"
            ]
        }
    }
  storageInitializer: |-
    {
        "image" : "registry.cn-shanghai.aliyuncs.com/pai_product/k8s:gcr.io-kfserving-storage-initializer-v0.3.0",
        "memoryRequest": "100Mi",
        "memoryLimit": "1Gi",
        "cpuRequest": "100m",
        "cpuLimit": "1"
    }
  transformers: |-
    {
    }
kind: ConfigMap
metadata:
  name: inferenceservice-config
