apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: spartakus
  app.kubernetes.io/name: spartakus
kind: Kustomization
namespace: kubeflow
resources:
- overlays/application/application.yaml
