apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameprefix: ml-pipeline-
commonLabels:
  app: ml-pipeline-persistenceagent
resources:
- clusterrole-binding.yaml
- clusterrole.yaml
- deployment.yaml
- service-account.yaml
images:
- name: gcr.io/ml-pipeline/persistenceagent
  newTag: gcr.io-ml-pipeline-persistenceagent-0.2.5
  newName: registry.cn-shanghai.aliyuncs.com/pai_product/k8s
