apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
- namespace.yaml
- api-service.yaml
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- mutating-webhook-configuration.yaml
- service-account.yaml
- service.yaml
- validating-webhook-configuration.yaml
commonLabels:
  kustomize.component: cert-manager
images:
- name: quay.io/jetstack/cert-manager-controller
  newName: registry.cn-shanghai.aliyuncs.com/pai_product/k8s
  newTag: quay.io-jetstack-cert-manager-controller-v0.11.0
- name: quay.io/jetstack/cert-manager-webhook
  newName: registry.cn-shanghai.aliyuncs.com/pai_product/k8s
  newTag: quay.io-jetstack-cert-manager-webhook-v0.11.0
- name: quay.io/jetstack/cert-manager-cainjector
  newName: registry.cn-shanghai.aliyuncs.com/pai_product/k8s
  newTag: quay.io-jetstack-cert-manager-cainjector-v0.11.0
configMapGenerator:
- name: cert-manager-parameters
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: cert-manager-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace
configurations:
- params.yaml
