apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
commonLabels:
  kustomize.component: tf-job-operator
images:
- name: gcr.io/kubeflow-images-public/tf_operator
  newName: registry.cn-shanghai.aliyuncs.com/pai_product/k8s
  newTag: gcr.io-kubeflow-images-public-tf_operator-vmaster-gda226016
