apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: seldon
  app.kubernetes.io/name: seldon-core-operator
kind: Kustomization
namespace: kubeflow
resources:
- overlays/application/application.yaml
