apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: cert-manager
  app.kubernetes.io/name: cert-manager
  kustomize.component: cert-manager
configurations:
- overlays/application/params.yaml
kind: Kustomization
namespace: cert-manager
resources:
- overlays/self-signed/cluster-issuer.yaml
- overlays/application/application.yaml
